MODEL:
  TYPE: vit
  NAME: vit_small
  DROP_RATE: 0.1
  VIT:
    EMBED_DIM: 384
    PATCH_SIZE: 16
    DEPTH: 12
    NUM_HEADS: 6

TRAIN:
  EPOCHS: 100
  # START_EPOCH: 48
  BASE_LR: 1e-5

DATA:
  MEAN: (0.5, 0.5, 0.5)
  STD: (0.5, 0.5, 0.5)
